
# borrowed from this tutorial: dev.to/a-modern-developer-s-workflow-for-twine-4imp 

name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: Build game
        run: |
          go get github.com/tmedwards/tweego
          set PATH=%PATH%;%GOPATH%\bin
          tweego main.twee -o dist/index.html
        shell: cmd

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist